apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: b0hvz1mf0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/b0hvz1mf0-java-quarkus-gitops